#!/bin/bash

# QuickAI Vercel Deployment Checklist
# Run through each step systematically

echo "╔═════════════════════════════════════════════════════════════╗"
echo "║       QuickAI - Vercel Deployment Checklist               ║"
echo "╚═════════════════════════════════════════════════════════════╝"

# Step 1: Pre-Deployment
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: PRE-DEPLOYMENT CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] 1. Verify project structure:"
echo "    - QuickAI-main/"
echo "      ├── client/ (React frontend)"
echo "      └── server/ (Express backend)"

echo ""
echo "[ ] 2. Check node_modules installed:"
echo "    $ cd client && npm install && cd ../server && npm install && cd .."

echo ""
echo "[ ] 3. Verify Vercel config files exist:"
echo "    $ cat server/vercel.json"
echo "    $ cat client/vercel.json"

echo ""
echo "[ ] 4. Git setup:"
echo "    $ git init"
echo "    $ git add ."
echo "    $ git commit -m 'QuickAI for Vercel deployment'"
echo "    $ git branch -M main"
echo "    $ git remote add origin https://github.com/YOUR_USERNAME/quickai.git"
echo "    $ git push -u origin main"

# Step 2: Gather Credentials
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: GATHER ENVIRONMENT VARIABLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] DATABASE_URL from Neon:"
echo "    Go to neon.tech → Project → Copy connection string"
echo "    Format: postgresql://user:password@host/db"

echo ""
echo "[ ] Cloudinary credentials:"
echo "    Go to cloudinary.com → Dashboard → API Keys"
echo "    [ ] CLOUDINARY_CLOUD_NAME"
echo "    [ ] CLOUDINARY_API_KEY"
echo "    [ ] CLOUDINARY_API_SECRET"

echo ""
echo "[ ] Gemini API Key:"
echo "    Go to aistudio.google.com/app/apikey → Create key"

echo ""
echo "[ ] Clerk Keys:"
echo "    Go to dashboard.clerk.com → API Keys"
echo "    [ ] CLERK_PUBLISHABLE_KEY (pk_live_...)"
echo "    [ ] CLERK_SECRET_KEY (sk_live_...)"

# Step 3: Backend Deployment
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: DEPLOY BACKEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] Go to https://vercel.com/new"
echo "[ ] Import your GitHub repository"
echo "[ ] Select 'QuickAI' repository"
echo "[ ] Under 'Configure Project':"
echo "    [ ] Root Directory: 'server'"
echo "    [ ] Framework: 'Other'"
echo "    [ ] Build Command: (leave empty)"
echo "    [ ] Output Directory: (leave empty)"
echo ""
echo "[ ] Click 'Environment Variables'"
echo "    Add these variables:"
echo "    [ ] DATABASE_URL = (your neon url)"
echo "    [ ] CLOUDINARY_CLOUD_NAME = (value)"
echo "    [ ] CLOUDINARY_API_KEY = (value)"
echo "    [ ] CLOUDINARY_API_SECRET = (value)"
echo "    [ ] GEMINI_API_KEY = (value)"
echo "    [ ] CLERK_SECRET_KEY = (value)"
echo "    [ ] CLERK_PUBLISHABLE_KEY = (value)"
echo "    [ ] NODE_ENV = 'production'"
echo ""
echo "[ ] Click 'Deploy'"
echo "[ ] Wait for deployment to complete (3-5 minutes)"
echo "[ ] Copy your backend URL:"
echo "    Note: https://quickai-server-XXX.vercel.app"

# Step 4: Test Backend
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: TEST BACKEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] Test backend health:"
echo "    $ curl https://YOUR_BACKEND_URL/api/health"
echo "    Expected: { \"status\": \"OK\" }"
echo ""
echo "[ ] Check Vercel logs for errors:"
echo "    Go to Vercel Dashboard → Deployments → View Logs"

# Step 5: Frontend Deployment
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: DEPLOY FRONTEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] Go to https://vercel.com/new again"
echo "[ ] Select same GitHub repository"
echo "[ ] Under 'Configure Project':"
echo "    [ ] Root Directory: 'client'"
echo "    [ ] Framework: 'Vite'"
echo "    [ ] Build Command: 'npm run build'"
echo "    [ ] Output Directory: 'dist'"
echo "    [ ] Install Command: 'npm install'"
echo ""
echo "[ ] Click 'Environment Variables'"
echo "    Add these variables:"
echo "    [ ] VITE_CLERK_PUBLISHABLE_KEY = (your clerk public key)"
echo "    [ ] VITE_API_URL = (paste your backend URL from Step 3)"
echo "    [ ] VITE_NODE_ENV = 'production'"
echo ""
echo "[ ] Click 'Deploy'"
echo "[ ] Wait for deployment (2-3 minutes)"
echo "[ ] Copy your frontend URL:"
echo "    Note: https://quickai-XXX.vercel.app"

# Step 6: Final Testing
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: FINAL VERIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] Open frontend URL in browser:"
echo "    https://YOUR_FRONTEND_URL"
echo ""
echo "[ ] Check browser console (F12) for errors:"
echo "    Should see no red errors"
echo ""
echo "[ ] Test Clerk authentication:"
echo "    [ ] Try to sign up"
echo "    [ ] Try to sign in"
echo "    [ ] Check dashboard loads"
echo ""
echo "[ ] Test API connectivity:"
echo "    Go to DevTools → Network tab"
echo "    Make a request and verify:"
echo "    [ ] Status: 200"
echo "    [ ] No CORS errors"
echo ""
echo "[ ] Test image upload (if applicable)"
echo "[ ] Check database queries work"

# Step 7: Production Setup
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 7: PRODUCTION SETUP (OPTIONAL)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[ ] Set up custom domain (optional):"
echo "    Go to Vercel Dashboard → Settings → Domains"
echo "    Add your custom domain (costs ~$12/year)"
echo ""
echo "[ ] Enable Auto-deployments:"
echo "    Every 'git push' now automatically deploys!"
echo ""
echo "[ ] Set up environment variables for production:"
echo "    Go to Settings → Environment Variables"
echo "    Mark as 'Production' only"
echo ""
echo "[ ] Backup credentials safely:"
echo "    Save API keys in secure password manager"
echo ""
echo "[ ] Monitor application:"
echo "    Set up error tracking (Sentry, etc.)"
echo "    Monitor Vercel Analytics"

# Success
echo ""
echo "╔═════════════════════════════════════════════════════════════╗"
echo "║                   ✅ DEPLOYMENT COMPLETE                   ║"
echo "╚═════════════════════════════════════════════════════════════╝"
echo ""
echo "Your QuickAI application is now live!"
echo ""
echo "Frontend:  https://YOUR_FRONTEND_URL"
echo "Backend:   https://YOUR_BACKEND_URL"
echo ""
echo "Next steps:"
echo "1. Share your frontend URL with users"
echo "2. Monitor the application regularly"
echo "3. Keep API keys secure"
echo "4. Update code and push to GitHub for auto-deploy"
echo ""
